#!/bin/bash

#status=`amixer | grep -E "Mono: Playback [-1-9]{1,3}" | awk -F'[ ]' '{ print $8 }' | sed 's/\[//g' | sed 's/\]//g'`
#
#if [ $status = "on" ]; then
#    amixer | grep -E "Mono: Playback [0-9]{1,3}" | awk -F'[ ]' '{ print $6 }' | sed 's/\[//g' | sed 's/\]//g'
#else
#    echo "Muted"
#fi

if $(pamixer --get-mute) ; then
        echo "Muted"
else
	echo `pamixer --get-volume`%
fi


