#!/bin/bash

# Two greps if there is no network connection at all
status=`curl https://am.i.mullvad.net/connected 2> /dev/null | grep Mullvad | grep not`

if [ "$?" == "1" ]; then
    echo "Connected"
else
    echo "Disconnected"
    echo "#ff002b"
fi
